#!/bin/bash

# Script to add Widget Extension target to EPL Forecast project
# This should be run from Xcode or Terminal

echo "To add the Widget Extension to your EPL Forecast project:"
echo ""
echo "1. Open EPLForecast.xcodeproj in Xcode"
echo "2. In Xcode, go to File > New > Target..."
echo "3. Choose 'Widget Extension' from iOS templates"
echo "4. Use these settings:"
echo "   - Product Name: EPLForecastWidget"  
echo "   - Bundle Identifier: com.LoudSteve.EplForecast.EPLForecast.EPLForecastWidget"
echo "   - Language: Swift"
echo "   - Include Configuration Intent: NO"
echo "5. Click Finish"
echo "6. Delete the template files that Xcode creates:"
echo "   - EPLForecastWidget.swift (we have our own)"
echo "   - EPLForecastWidgetBundle.swift (we have our own)"
echo "7. Add our widget files to the new target:"
echo "   - Right-click EPLForecastWidget folder"
echo "   - Add Files to EPLForecastWidget"
echo "   - Select: EPLForecastWidget/EPLForecastWidget.swift"
echo "   - Select: EPLForecastWidget/EPLForecastWidgetBundle.swift"
echo "8. Update widget target capabilities:"
echo "   - Select EPLForecastWidget target"
echo "   - Go to Signing & Capabilities"
echo "   - Add App Groups capability"
echo "   - Add: group.com.LoudSteve.EplForecast.EPLForecast"
echo "9. Set Code Signing Entitlements:"
echo "   - Build Settings > Code Signing Entitlements"
echo "   - Set to: EPLForecastWidget/EPLForecastWidget.entitlements"
echo ""
echo "Then build and run - the widget should appear in the widget gallery!"