name: Deploy Web App

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - 'infrastructure/web-hosting.yaml'
      - '.github/workflows/deploy-web.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - prod
        default: prod

env:
  AWS_REGION: us-west-2

jobs:
  deploy-infrastructure:
    name: Deploy CloudFront + S3 Infrastructure
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'prod' }}
    outputs:
      bucket-name: ${{ steps.stack-outputs.outputs.bucket-name }}
      distribution-id: ${{ steps.stack-outputs.outputs.distribution-id }}
      website-url: ${{ steps.stack-outputs.outputs.website-url }}

    steps:
    - uses: actions/checkout@v4

    - name: Set environment
      id: set-env
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
        else
          echo "environment=prod" >> $GITHUB_OUTPUT
        fi

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ steps.set-env.outputs.environment == 'prod' && secrets.AWS_ACCESS_KEY_ID_PROD || secrets.AWS_ACCESS_KEY_ID_DEV }}
        aws-secret-access-key: ${{ steps.set-env.outputs.environment == 'prod' && secrets.AWS_SECRET_ACCESS_KEY_PROD || secrets.AWS_SECRET_ACCESS_KEY_DEV }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy CloudFormation stack
      run: |
        aws cloudformation deploy \
          --template-file infrastructure/web-hosting.yaml \
          --stack-name epl-forecast-web-${{ steps.set-env.outputs.environment }} \
          --parameter-overrides \
            Environment=${{ steps.set-env.outputs.environment }} \
          --capabilities CAPABILITY_IAM \
          --region ${{ env.AWS_REGION }} \
          --no-fail-on-empty-changeset

    - name: Get stack outputs
      id: stack-outputs
      run: |
        BUCKET_NAME=$(aws cloudformation describe-stacks \
          --stack-name epl-forecast-web-${{ steps.set-env.outputs.environment }} \
          --region ${{ env.AWS_REGION }} \
          --query 'Stacks[0].Outputs[?OutputKey==`BucketName`].OutputValue' \
          --output text)

        DISTRIBUTION_ID=$(aws cloudformation describe-stacks \
          --stack-name epl-forecast-web-${{ steps.set-env.outputs.environment }} \
          --region ${{ env.AWS_REGION }} \
          --query 'Stacks[0].Outputs[?OutputKey==`DistributionId`].OutputValue' \
          --output text)

        WEBSITE_URL=$(aws cloudformation describe-stacks \
          --stack-name epl-forecast-web-${{ steps.set-env.outputs.environment }} \
          --region ${{ env.AWS_REGION }} \
          --query 'Stacks[0].Outputs[?OutputKey==`WebsiteURL`].OutputValue' \
          --output text)

        echo "bucket-name=$BUCKET_NAME" >> $GITHUB_OUTPUT
        echo "distribution-id=$DISTRIBUTION_ID" >> $GITHUB_OUTPUT
        echo "website-url=$WEBSITE_URL" >> $GITHUB_OUTPUT

        echo "Bucket: $BUCKET_NAME"
        echo "Distribution: $DISTRIBUTION_ID"
        echo "URL: $WEBSITE_URL"

  deploy-web-app:
    name: Deploy Web App Files
    runs-on: ubuntu-latest
    needs: deploy-infrastructure
    environment: ${{ github.event.inputs.environment || 'prod' }}

    steps:
    - uses: actions/checkout@v4

    - name: Set environment
      id: set-env
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
        else
          echo "environment=prod" >> $GITHUB_OUTPUT
        fi

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ steps.set-env.outputs.environment == 'prod' && secrets.AWS_ACCESS_KEY_ID_PROD || secrets.AWS_ACCESS_KEY_ID_DEV }}
        aws-secret-access-key: ${{ steps.set-env.outputs.environment == 'prod' && secrets.AWS_SECRET_ACCESS_KEY_PROD || secrets.AWS_SECRET_ACCESS_KEY_DEV }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Sync web files to S3
      run: |
        aws s3 sync web/ s3://${{ needs.deploy-infrastructure.outputs.bucket-name }}/ \
          --exclude "*.md" \
          --exclude ".gitignore" \
          --exclude "vercel.json" \
          --delete \
          --cache-control "public, max-age=300, s-maxage=300" \
          --region ${{ env.AWS_REGION }}

        echo "✅ Web files synced to S3"

    - name: Set correct content types
      run: |
        # Set content type for HTML files
        aws s3 cp s3://${{ needs.deploy-infrastructure.outputs.bucket-name }}/index.html \
          s3://${{ needs.deploy-infrastructure.outputs.bucket-name }}/index.html \
          --content-type "text/html; charset=utf-8" \
          --metadata-directive REPLACE \
          --cache-control "public, max-age=300, s-maxage=300" \
          --region ${{ env.AWS_REGION }}

        # Set content type for CSS files
        aws s3 cp s3://${{ needs.deploy-infrastructure.outputs.bucket-name }}/styles.css \
          s3://${{ needs.deploy-infrastructure.outputs.bucket-name }}/styles.css \
          --content-type "text/css; charset=utf-8" \
          --metadata-directive REPLACE \
          --cache-control "public, max-age=86400, s-maxage=86400" \
          --region ${{ env.AWS_REGION }}

        # Set content type for JS files
        aws s3 cp s3://${{ needs.deploy-infrastructure.outputs.bucket-name }}/app.js \
          s3://${{ needs.deploy-infrastructure.outputs.bucket-name }}/app.js \
          --content-type "application/javascript; charset=utf-8" \
          --metadata-directive REPLACE \
          --cache-control "public, max-age=86400, s-maxage=86400" \
          --region ${{ env.AWS_REGION }}

        echo "✅ Content types set correctly"

    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ needs.deploy-infrastructure.outputs.distribution-id }} \
          --paths "/*" \
          --region ${{ env.AWS_REGION }}

        echo "✅ CloudFront cache invalidated"

    - name: Deployment summary
      run: |
        echo "## 🎉 Web App Deployment Complete!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Environment:** ${{ steps.set-env.outputs.environment }}" >> $GITHUB_STEP_SUMMARY
        echo "**S3 Bucket:** ${{ needs.deploy-infrastructure.outputs.bucket-name }}" >> $GITHUB_STEP_SUMMARY
        echo "**CloudFront Distribution:** ${{ needs.deploy-infrastructure.outputs.distribution-id }}" >> $GITHUB_STEP_SUMMARY
        echo "**Website URL:** ${{ needs.deploy-infrastructure.outputs.website-url }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "The web app is now live at:" >> $GITHUB_STEP_SUMMARY
        echo "🔗 [${{ needs.deploy-infrastructure.outputs.website-url }}](${{ needs.deploy-infrastructure.outputs.website-url }})" >> $GITHUB_STEP_SUMMARY

        echo ""
        echo "================================================"
        echo "✅ Deployment successful!"
        echo "🌐 Website URL: ${{ needs.deploy-infrastructure.outputs.website-url }}"
        echo "================================================"
